name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
      # - name: Set SDKROOT
      #   run: echo "SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)" >> $GITHUB_ENV
      # - name: Set MACOSX_DEPLOYMENT_TARGET
      #   run: echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)" >> $GITHUB_ENV
      - run: cargo build --release --target aarch64-apple-darwin

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install gcc-multilib
      - uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo build --release

