name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Rustup
      run: |
        rm $(which rustfmt)
        rm $(which cargo-fmt)
        rustup self update
        rustup update
        rustup show
      # rustup toolchain install stable --profile minimal
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --locked
    - name: Formatting
      run: cargo fmt --check
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Berlin"
    - name: Tests
      run: cargo test
